#!/usr/bin/env python3
"""Generate an improved skill file by integrating validated lessons.

Uses claude -p to rewrite the skill content with lessons woven in.
Falls back to appending a '## Learned patterns' section if the user rejects.
"""

import json
import subprocess
import sys
import os


def generate_evolved_skill(skill_content, lessons, model_cmd="claude -p"):
    """Call claude -p to generate an improved skill.

    Args:
        skill_content: Current skill .md file content
        lessons: List of lesson dicts (text, confidence, source_projects)
        model_cmd: Command to invoke Claude

    Returns:
        str: The full updated skill content, or None on failure
    """
    lessons_text = "\n".join(
        f"- [{l.get('confidence', 0):.2f}] {l['text']} "
        f"(from: {', '.join(l.get('source_projects', ['unknown']))})"
        for l in sorted(lessons, key=lambda x: x.get("confidence", 0), reverse=True)
    )

    prompt = f"""You are improving a Claude Code skill based on validated lessons learned from real usage. The skill's current content and the lessons are provided below.

RULES:
- Integrate lessons naturally into the existing content
- Don't create a separate "lessons" section — weave guidance into the flow where it belongs
- Preserve the skill's existing structure, voice, and formatting
- Higher-confidence lessons should be treated as more authoritative
- If a lesson contradicts existing guidance, the lesson wins (it's from real usage)
- Don't add preamble or meta-commentary
- Output the complete updated skill content, nothing else

CURRENT SKILL CONTENT:
<skill>
{skill_content}
</skill>

LESSONS TO INTEGRATE (sorted by confidence):
<lessons>
{lessons_text}
</lessons>"""

    try:
        result = subprocess.run(
            ["bash", "-c", model_cmd],
            input=prompt,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
    except Exception as e:
        sys.stderr.write(f"[skill-evolution] claude call failed: {e}\n")

    return None


def generate_append_fallback(lessons):
    """Generate a '## Learned patterns' section for appending.

    Args:
        lessons: List of lesson dicts

    Returns:
        str: Markdown section to append
    """
    lines = [
        "\n\n## Learned patterns\n",
        "<!-- Auto-generated by autocontext skill evolution. Do not edit manually. -->\n",
    ]
    for l in sorted(lessons, key=lambda x: x.get("confidence", 0), reverse=True):
        sources = ", ".join(l.get("source_projects", ["unknown"]))
        lines.append(f"\n- **[{l.get('confidence', 0):.2f}]** {l['text']}")
        lines.append(f"  _Sources: {sources}_")

    return "\n".join(lines) + "\n"
