"""Contract tests for the no-ai-attribution PreToolUse hook.

The hook blocks a git/gh command that would write AI authorship credit into the
project record, before it runs. It reads the Claude Code PreToolUse payload on
stdin and exits 2 to deny (reason on stderr) or 0 to allow.

These tests drive the implementation: they define exactly which command shapes
must block, which must pass, and how the hook fails open. Run:
    python -m pytest hooks/tests/test_no_ai_attribution.py -q
"""
import json
import os
import subprocess
import sys
from pathlib import Path

HOOK = Path(__file__).resolve().parent.parent / "no-ai-attribution.py"

DENY = 2
ALLOW = 0


def run(command, tool_name="Bash", cwd=None, raw_stdin=None, timeout=30, env=None):
    """Invoke the hook as a subprocess with a PreToolUse payload; return CompletedProcess.

    timeout guards the never-wedge contract: if the hook hangs (e.g. reading a FIFO),
    subprocess.run raises TimeoutExpired and kills the child, so a hang fails the test
    loudly instead of freezing the suite. `env`, when given, is merged over the current
    environment for the child, so a test can set HOME to exercise `~` expansion.
    """
    if raw_stdin is None:
        payload = {"tool_name": tool_name, "tool_input": {"command": command}}
        if cwd is not None:
            payload["cwd"] = str(cwd)
        stdin = json.dumps(payload)
    else:
        stdin = raw_stdin
    return subprocess.run(
        [sys.executable, str(HOOK)],
        input=stdin,
        capture_output=True,
        text=True,
        timeout=timeout,
        env=({**os.environ, **env} if env else None),
    )


def assert_blocked(r):
    # A real deny is exit 2 with the hook's own reason on stderr. Requiring the
    # sentinel distinguishes a genuine block from a crash (a missing script also
    # exits 2, with a traceback instead of the reason).
    assert r.returncode == DENY and "no-ai-attribution" in r.stderr.lower(), (
        r.returncode,
        r.stderr,
    )


def assert_allowed(r):
    assert r.returncode == ALLOW, (r.returncode, r.stderr)


# --------------------------------------------------------------------------
# MUST BLOCK: inline / body attribution (the message-text surface)
# --------------------------------------------------------------------------

def test_block_commit_inline_generated_with():
    r = run('git commit -m "Fix parser\n\n\U0001F916 Generated with Claude Code"')
    assert_blocked(r)


def test_block_commit_inline_coauthored_trailer_in_message():
    r = run('git commit -m "Fix parser\n\nCo-Authored-By: GPT-4 <noreply@openai.com>"')
    assert_blocked(r)


def test_block_commit_am_cluster_robot_emoji():
    r = run('git commit -am "\U0001F916 tidy up"')
    assert_blocked(r)


def test_block_chained_second_commit_attributed():
    r = run('git add -A && git commit -am "Generated by Claude"')
    assert_blocked(r)


def test_block_pr_create_body_generated_with():
    r = run('gh pr create --body "Generated with Claude Code"')
    assert_blocked(r)


def test_block_pr_create_title_written_by():
    r = run('gh pr create --title "Written by Claude" --body "clean body"')
    assert_blocked(r)


def test_block_pr_comment_coauthored_with():
    r = run('gh pr comment 5 --body "Co-authored with Claude"')
    assert_blocked(r)


def test_block_issue_comment_ai_generated():
    r = run('gh issue comment 7 --body "AI-generated summary. \U0001F916"')
    assert_blocked(r)


def test_block_pr_review_body_attribution():
    r = run('gh pr review 5 --body "Written by Copilot"')
    assert_blocked(r)


# --------------------------------------------------------------------------
# MUST BLOCK: the four conceded flag-level bypasses (#177)
# --------------------------------------------------------------------------

def test_block_commit_trailer_flag_model():
    r = run("git commit -m \"Fix\" --trailer 'Co-Authored-By: Claude <noreply@anthropic.com>'")
    assert_blocked(r)


def test_block_commit_author_flag_bot_email():
    r = run("git commit -m \"Fix\" --author='Claude <bot@example.com>'")
    assert_blocked(r)


def test_block_commit_author_flag_tool_name_human_email():
    # The author field is authorship by definition: a tool token blocks even with a
    # non-bot email.
    r = run("git commit -m \"Fix\" --author='Codex <someone@example.com>'")
    assert_blocked(r)


def test_block_pr_edit_body_attribution():
    r = run('gh pr edit 3 --body "Written by ChatGPT"')
    assert_blocked(r)


def test_block_pr_create_template_file_attributed(tmp_path):
    tpl = tmp_path / "T.md"
    tpl.write_text("## Summary\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n")
    r = run("gh pr create --template T.md", cwd=tmp_path)
    assert_blocked(r)


def test_block_pr_edit_body_file_robot_emoji(tmp_path):
    body = tmp_path / "B.md"
    body.write_text("Updates the parser.\n\n\U0001F916 Generated with Claude Code\n")
    r = run("gh pr edit 3 --body-file B.md", cwd=tmp_path)
    assert_blocked(r)


def test_block_commit_file_message_attributed(tmp_path):
    msg = tmp_path / "MSG"
    msg.write_text("Fix the parser\n\n\U0001F916 Generated with Claude Code\n")
    r = run("git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


# --------------------------------------------------------------------------
# MUST BLOCK: environment-variable prefixes (the command word is not seg[0])
# --------------------------------------------------------------------------

def test_block_pr_create_env_prefixed_body():
    # GH_TOKEN=... gh pr create is a common scripted form; the command word is not
    # the first token, so the hook must step over the assignment to find it.
    r = run('GH_TOKEN=xxx gh pr create --body "Generated with Claude Code"')
    assert_blocked(r)


def test_block_commit_env_identity_tool_name():
    # Setting authorship through the environment is the twin of --author.
    r = run('GIT_AUTHOR_NAME=Claude git commit -m "Fix the parser"')
    assert_blocked(r)


def test_block_commit_env_wrapper_identity():
    # Same authorship bypass through the `env` command wrapper.
    r = run('env GIT_AUTHOR_NAME=Claude git commit -m "Fix the parser"')
    assert_blocked(r)


def test_block_ai_assisted_standalone_byline():
    # A standalone "AI-assisted" sign-off line is a byline, not subject matter.
    r = run('git commit -m "Refactor auth\n\nAI-assisted"')
    assert_blocked(r)


def test_block_commit_dash_c_identity_config():
    # git -c user.name=... sets the commit identity inline, the same as --author.
    r = run('git -c user.name=Claude -c user.email=bot@example.com commit -m "Fix parser"')
    assert_blocked(r)


def test_block_commit_env_split_string_identity():
    # env -S packs the command into one re-split string; the inner identity must be seen.
    r = run('env -S "GIT_AUTHOR_NAME=Claude git commit -m Fix"')
    assert_blocked(r)


# --------------------------------------------------------------------------
# MUST BLOCK: shell syntax that hides the command word from a naive tokenizer
# --------------------------------------------------------------------------

def test_block_spaceless_operator_chained_commit():
    # No spaces around && : plain shlex.split leaves "-A&&" as one token.
    r = run('git add -A&& git commit -m "Generated by Claude"')
    assert_blocked(r)


def test_block_spaceless_semicolon_commit():
    r = run('true;git commit -m "Written by Claude"')
    assert_blocked(r)


def test_block_subshell_wrapped_commit():
    r = run('(git commit -m "Generated by Claude")')
    assert_blocked(r)


def test_block_gh_global_repo_flag_before_pr():
    r = run('gh -R owner/repo pr create --body "Generated with Claude Code"')
    assert_blocked(r)


def test_block_gh_repo_equals_flag_before_comment():
    r = run('gh --repo=owner/repo pr comment 5 --body "Written by ChatGPT"')
    assert_blocked(r)


def test_block_gh_value_taking_global_before_pr():
    # A value-taking global (here --hostname) must not be mistaken for the group; the
    # command is identified by the pr+create tokens, not by position.
    r = run('gh --hostname github.com pr create --body "Generated with Claude Code"')
    assert_blocked(r)


def test_block_gh_issue_create_body_attributed():
    r = run('gh issue create --title "Bug" --body "\U0001F916 Generated with Claude Code"')
    assert_blocked(r)


# --------------------------------------------------------------------------
# MUST ALLOW: legitimate tool mentions, human authorship, unwatched commands
# --------------------------------------------------------------------------

def test_allow_spaceless_operator_clean_commit():
    r = run('git add -A&& git commit -m "Fix the parser"')
    assert_allowed(r)


def test_allow_gh_global_repo_flag_clean_body():
    r = run('gh -R owner/repo pr create --title "Add X" --body "Adds X. Verify by running it."')
    assert_allowed(r)


def test_allow_commit_dash_c_nonidentity_config():
    r = run('git -c core.editor=vim commit -m "Fix the parser"')
    assert_allowed(r)


def test_allow_commit_dash_c_human_identity():
    r = run('git -c user.name="Jane Doe" commit -m "Fix the parser"')
    assert_allowed(r)


def test_allow_robot_emoji_as_subject_matter():
    # A robot emoji embedded in prose describes the subject, not authorship.
    r = run('git commit -m "Fix \U0001F916 emoji rendering in Slack messages"')
    assert_allowed(r)


def test_allow_robot_emoji_trailing_decoration_no_cue():
    # A trailing robot emoji with no attribution cue on its line is decoration, not a
    # byline.
    r = run('git commit -m "Restart the bot \U0001F916"')
    assert_allowed(r)


def test_allow_ai_generated_as_subject_matter():
    # Journalism repos discuss AI-generated content constantly; the phrase embedded in
    # a sentence describes the subject of the change, not who authored it.
    r = run('git commit -m "Detect AI-generated images in uploads"')
    assert_allowed(r)


def test_allow_ai_assisted_as_subject_matter():
    r = run('gh pr create --title "Analysis" --body "Add AI-assisted analysis to the dashboard"')
    assert_allowed(r)


def test_allow_env_prefixed_clean_body():
    r = run('GH_TOKEN=xxx gh pr create --title "Add X" --body "Adds X. Verify by running the tests."')
    assert_allowed(r)


def test_allow_env_identity_human():
    r = run('GIT_AUTHOR_NAME="Jane Doe" git commit -m "Fix the parser"')
    assert_allowed(r)

def test_allow_commit_subject_names_tool():
    r = run('git commit -m "Fix the Claude API client parser"')
    assert_allowed(r)


def test_allow_pr_body_documents_tool():
    r = run('gh pr create --title "Docs" --body "Document the Claude API client and OpenAI fallback"')
    assert_allowed(r)


def test_allow_commit_author_human():
    r = run("git commit -m \"Fix\" --author='Jane Doe <jane@example.com>'")
    assert_allowed(r)


def test_allow_commit_trailer_human_coauthor():
    r = run("git commit -m \"Fix\" --trailer 'Co-Authored-By: Jane Doe <jane@example.com>'")
    assert_allowed(r)


def test_allow_commit_author_github_noreply_not_bot():
    # The repo's own author convention: NNN+user@users.noreply.github.com must not
    # read as a bot email.
    r = run("git commit -m \"Fix\" --author='Jane <27182+jane@users.noreply.github.com>'")
    assert_allowed(r)


def test_allow_verb_with_by_no_tool_token():
    # "built"/"written"/"by" are common words; without a tool token nearby they are
    # not attribution.
    r = run('git commit -m "Built by the team, written by hand"')
    assert_allowed(r)


def test_allow_clean_pr_body_verify_by_running():
    r = run('gh pr create --title "Add X" --body "Adds X. Verify by running the tests."')
    assert_allowed(r)


def test_allow_non_watched_command():
    r = run("ls -la")
    assert_allowed(r)


def test_allow_git_log_author_grep_not_a_commit():
    r = run("git log --author=Claude")
    assert_allowed(r)


def test_allow_commit_file_from_stdin_dash():
    r = run("git commit -F -")
    assert_allowed(r)


def test_allow_bare_commit_editor():
    r = run("git commit")
    assert_allowed(r)


def test_allow_pr_create_template_file_clean(tmp_path):
    tpl = tmp_path / "T.md"
    tpl.write_text("## Summary\n\nExplains the change and how to verify it.\n")
    r = run("gh pr create --template T.md", cwd=tmp_path)
    assert_allowed(r)


# --------------------------------------------------------------------------
# MUST BLOCK: shell structure a token stream erases (newline separators, cd)
# --------------------------------------------------------------------------

def test_block_newline_separated_commit():
    # A literal newline separates two commands the same as `;`. shlex drops it as
    # whitespace, so the attributed second command must still be seen.
    r = run('printf ok\ngit commit -m "Written by ChatGPT"')
    assert_blocked(r)


def test_allow_newline_separated_clean_commits():
    # The common multiline form: separate clean commands on their own lines.
    r = run('git add -A\ngit commit -m "Fix the parser"')
    assert_allowed(r)


def test_block_cd_then_relative_file_commit(tmp_path):
    # `cd repo && git commit -F MSG` resolves MSG in repo/, not the payload cwd.
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Written by ChatGPT\n")
    r = run("cd repo && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_git_dash_C_relative_file(tmp_path):
    # `git -C repo` changes the directory relative file args resolve against.
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("\U0001F916 Generated with Claude Code\n")
    r = run("git -C repo commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_allow_cd_then_relative_file_clean(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Fix the parser\n")
    r = run("cd repo && git commit -F MSG", cwd=tmp_path)
    assert_allowed(r)


def test_block_env_split_string_attached():
    # env -S accepts the attached form `-S'...'`, not only `-S "..."`.
    r = run("env -S'GIT_AUTHOR_NAME=Claude git commit -m Fix'")
    assert_blocked(r)


# --------------------------------------------------------------------------
# MUST BLOCK: gh edit title, gh issue edit, and more attribution connectors
# --------------------------------------------------------------------------

def test_block_pr_edit_title_attribution():
    # gh pr edit --title writes to the record too, not only --body.
    r = run('gh pr edit 3 --title "Written by ChatGPT"')
    assert_blocked(r)


def test_block_issue_edit_body_attribution():
    r = run('gh issue edit 3 --body "Written by ChatGPT"')
    assert_blocked(r)


def test_block_commit_generated_using_connector():
    r = run('git commit -m "Generated using Claude Code"')
    assert_blocked(r)


def test_block_commit_generated_via_connector():
    r = run('git commit -m "Generated via ChatGPT"')
    assert_blocked(r)


def test_block_byline_generated_with_still_blocks():
    # Regression: the canonical trailing byline stays blocked after the byline is
    # constrained to line-leading position (the fix for the subject-matter allow).
    r = run('git commit -m "Fix parser\n\nGenerated with Claude Code"')
    assert_blocked(r)


# --------------------------------------------------------------------------
# MUST ALLOW: an attribution verb + tool as mid-sentence subject matter
# --------------------------------------------------------------------------

def test_allow_generated_by_tool_as_subject_matter():
    # "summaries generated by Claude" describes what the change handles, not who wrote
    # the commit. In an AI-focused repo this phrasing is common and must pass.
    r = run('git commit -m "Handle summaries generated by Claude"')
    assert_allowed(r)


def test_allow_pr_body_content_written_by_model_as_subject():
    r = run('gh pr create --title "Moderation" --body "Flag posts written by GPT bots"')
    assert_allowed(r)


# --------------------------------------------------------------------------
# Named-file reads: bounded and regular-file-only (never wedge, never OOM)
# --------------------------------------------------------------------------

def test_fifo_body_file_fails_open_without_hanging(tmp_path):
    # A FIFO body-file would block a naive read forever. The hook must treat a
    # non-regular file as unreadable and fail open, returning quickly.
    import os
    fifo = tmp_path / "PIPE"
    os.mkfifo(fifo)
    r = run("gh pr create --body-file PIPE", cwd=tmp_path, timeout=15)
    assert_allowed(r)


def test_large_regular_body_file_with_early_attribution_blocks(tmp_path):
    # A large but regular file is read up to the cap; attribution near the top is
    # still caught, and the read does not exhaust memory.
    body = tmp_path / "BIG.md"
    body.write_text("\U0001F916 Generated with Claude Code\n" + ("filler line\n" * 200000))
    r = run("gh pr create --body-file BIG.md", cwd=tmp_path)
    assert_blocked(r)


# --------------------------------------------------------------------------
# Fail open: never wedge a session on a payload the hook cannot read
# --------------------------------------------------------------------------

def test_failopen_malformed_json():
    r = run(None, raw_stdin="{ this is not json")
    assert_allowed(r)


def test_failopen_empty_stdin():
    r = run(None, raw_stdin="")
    assert_allowed(r)


def test_failopen_non_bash_tool():
    r = run('git commit -m "\U0001F916 Generated with Claude Code"', tool_name="Write")
    assert_allowed(r)


def test_failopen_missing_tool_input():
    r = run(None, raw_stdin=json.dumps({"tool_name": "Bash"}))
    assert_allowed(r)


def test_failopen_missing_template_file_allows(tmp_path):
    # A named template that does not exist cannot be read; do not wedge the command.
    r = run("gh pr create --template MISSING.md", cwd=tmp_path)
    assert_allowed(r)


def test_unbalanced_quotes_falls_back_to_raw_scan():
    # shlex cannot tokenize this, but the attribution is still visible in the raw
    # command, so it must still block.
    r = run('git commit -m "\U0001F916 Generated with Claude Code')
    assert_blocked(r)


# --------------------------------------------------------------------------
# MUST BLOCK: shell forms a stricter reviewer found still slipped through
# --------------------------------------------------------------------------

def test_coauthor_scan_is_not_quadratic_on_blank_lines():
    # A clean commit message of many blank lines must be cleared quickly. The quadratic
    # case is the non-matching one: a leading ^\s* in the Co-Authored-By regex under re.M
    # greedily eats to the end from every line anchor and fails, rescanning O(n^2). A
    # tight timeout hangs on that; the linear ^[ \t]* form returns in well under a second.
    # (A message that does end in a matching Co-Authored-By line matches on the first
    # anchor and is fast even with the bug, so it would not exercise the backtracking.)
    msg = "\n" * 32000 + "Fixed the parser"
    r = run('git commit -m "%s"' % msg, timeout=5)
    assert_allowed(r)


def test_block_env_chdir_attached_relative_file(tmp_path):
    # env -Crepo (attached short form) sets the run dir the same as env -C repo, so a
    # relative -F file resolves in repo/, not the payload cwd.
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Generated with Claude Code\n")
    r = run("env -Crepo git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_env_double_dash_then_identity():
    # env -- ends option parsing but still reads NAME=value operands as assignments, so
    # the identity var after -- must reach the same check as a bare identity prefix.
    r = run("env -- GIT_AUTHOR_NAME=Claude git commit -m Fix")
    assert_blocked(r)


def test_block_commit_ansi_c_quoted_byline():
    # $'...\n...' is ANSI-C quoting: bash decodes \n to a real newline and commits a
    # real trailing byline, but shlex keeps the literal backslash-n, so the byline slips
    # unless the escapes are decoded before the line-anchored check.
    r = run("git commit -m $'Fix parser\\n\\nGenerated with Claude Code'")
    assert_blocked(r)


def test_block_subshell_cd_does_not_hide_payload_cwd_file(tmp_path):
    # (cd repo) runs in a subshell, so its cd does not move the later git commit, which
    # still reads ./MSG at the payload cwd. Tracking the cd as if it persisted would read
    # the clean repo/MSG and miss the attributed ./MSG.
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Fix the parser\n")
    (tmp_path / "MSG").write_text("Generated with Claude Code\n")
    r = run("(cd repo); git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_cd_to_missing_dir_still_checks_payload_cwd(tmp_path):
    # A failed `cd nonexistent` leaves the shell in the payload cwd, where git reads the
    # attributed ./MSG. Switching the effective dir to the missing target would read
    # nothing and miss it.
    (tmp_path / "MSG").write_text("Generated with Claude Code\n")
    r = run("cd nonexistent; git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_allow_cd_clean_file_in_both_dirs(tmp_path):
    # Checking both the tracked dir and the payload cwd must not block when both files
    # are clean: the legitimate cd-into-repo commit still passes.
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Fix the parser\n")
    (tmp_path / "MSG").write_text("Fix the parser\n")
    r = run("cd repo && git commit -F MSG", cwd=tmp_path)
    assert_allowed(r)


# --------------------------------------------------------------------------
# MUST BLOCK: codex-connector PR #193 review findings (bot round on PR D)
# --------------------------------------------------------------------------

def test_block_exported_git_identity_across_segments():
    # `export GIT_AUTHOR_NAME=Claude; git commit` sets the identity in the shell for the
    # later commit, the same authorship surface as an inline prefix. The export lives in a
    # separate segment, so the commit segment must pick it up across the `;`.
    r = run("export GIT_AUTHOR_NAME=Claude; git commit -m Fix")
    assert_blocked(r)


def test_allow_exported_clean_env_then_commit():
    # A clean export must not poison a later clean commit: only an identity var naming a
    # tool blocks, and GH_TOKEN is not an identity var.
    r = run("export GH_TOKEN=abc123; git commit -m 'Fix the parser'")
    assert_allowed(r)


def test_block_ambient_exported_identity_before_bare_commit():
    # An identity var exported in the PARENT shell, before the hook even runs, is inherited
    # by a bare `git commit`, so the commit is authored by the tool with no assignment in
    # the command itself. Seeding identity tracking from the inherited environment is what
    # catches it; without that seed the bare commit reads as unwatched.
    r = run('git commit -m "Fix the parser"', env={"GIT_AUTHOR_NAME": "Claude"})
    assert_blocked(r)


def test_block_ambient_exported_identity_email():
    # The same inheritance holds for the email twin: an ambient GIT_COMMITTER_EMAIL naming
    # a bot is inherited by a bare commit and must block.
    r = run('git commit -m "Fix the parser"', env={"GIT_COMMITTER_EMAIL": "claude@anthropic.com"})
    assert_blocked(r)


def test_allow_ambient_human_identity_before_bare_commit():
    # Seeding from the environment must not misfire on a real person's identity: an ambient
    # GIT_AUTHOR_NAME that names no tool is a normal developer setup and must pass.
    r = run('git commit -m "Fix the parser"', env={"GIT_AUTHOR_NAME": "Jane Doe"})
    assert_allowed(r)


def test_allow_inline_human_reassignment_overrides_ambient_identity():
    # Reassignment is the third way the ambient identity is cleared, alongside env -i and
    # unset: an inline `GIT_AUTHOR_NAME=Jane git commit` overrides an ambient tool value for
    # that command (last-wins), so the effective author is the human and it must pass.
    r = run('GIT_AUTHOR_NAME="Jane Doe" git commit -m Fix', env={"GIT_AUTHOR_NAME": "Claude"})
    assert_allowed(r)


def test_allow_env_i_wipes_ambient_identity():
    # `env -i` starts the command with an empty environment, so an ambient tool identity is
    # NOT inherited by the commit it runs; seeding from the environment must still yield a
    # clean pass here, or env -i would falsely block.
    r = run('env -i git commit -m Fix', env={"GIT_AUTHOR_NAME": "Claude"})
    assert_allowed(r)


def test_allow_unset_clears_ambient_identity():
    # An `unset` of an ambient tool identity before the commit clears it, so the commit
    # carries no tool author and must pass even though the environment seeded the var.
    r = run('unset GIT_AUTHOR_NAME && git commit -m Fix', env={"GIT_AUTHOR_NAME": "Claude"})
    assert_allowed(r)


def test_block_ambient_identity_inside_nested_shell_runner():
    # A `bash -c 'git commit'` still inherits an ambient tool identity from the parent
    # shell, so the bypass of hiding the commit inside a shell runner must be closed: the
    # outer segment propagates its effective identity into the recursion.
    r = run("bash -c 'git commit -m Fix'", env={"GIT_AUTHOR_NAME": "Claude"})
    assert_blocked(r)


def test_allow_env_i_before_nested_shell_runner_commit():
    # A nested `bash -c 'git commit'` inherits the environment the OUTER command set up.
    # `env -i` cleared it, so the inner commit sees no tool identity: the propagated map is
    # empty and the commit must pass, not misfire on the wiped ambient value.
    r = run("env -i bash -c 'git commit -m Fix'", env={"GIT_AUTHOR_NAME": "Claude"})
    assert_allowed(r)


def test_allow_unset_before_nested_shell_runner_commit():
    # Same, via `unset`: the outer command dropped the ambient identity before running the
    # nested `bash -c 'git commit'`, so the propagated identity is empty and a clean commit
    # must pass.
    r = run("unset GIT_AUTHOR_NAME && bash -c 'git commit -m Fix'", env={"GIT_AUTHOR_NAME": "Claude"})
    assert_allowed(r)


def test_block_commit_tilde_home_message_file(tmp_path):
    # An unquoted `~/MSG` expands to $HOME/MSG before the command runs; resolving it
    # against cwd (reading cwd/~/MSG) would miss the byline in the real home file.
    home = tmp_path / "home"
    home.mkdir()
    (home / "MSG").write_text("Generated with Claude Code\n")
    work = tmp_path / "work"
    work.mkdir()
    r = run("git commit -F ~/MSG", cwd=work, env={"HOME": str(home)})
    assert_blocked(r)


def test_block_commit_ansi_c_single_line_byline():
    # $'Generated with Claude Code' is a whole-message ANSI-C quote: shlex leaves a literal
    # leading `$` on the token, which defeats the line-start byline anchor unless stripped.
    r = run("git commit -m $'Generated with Claude Code'")
    assert_blocked(r)


def test_block_commit_gpt_numeric_suffix():
    # A version-suffixed model name (GPT4, GPT-4o) must match the tool token; a bare `\bgpt\b`
    # stops at the letter/digit boundary and misses it.
    for msg in ("Generated with GPT4", "Generated with GPT-4o", "Written by GPT4o"):
        assert_blocked(run('git commit -m "%s"' % msg))


def test_block_commit_behind_shell_control_keyword():
    # A commit guarded by a control keyword still runs and still writes the byline; the
    # segment starts with `then`/`if`, hiding the `git` word unless the keyword is peeled.
    assert_blocked(run('if true; then git commit -m "Generated with Claude Code"; fi'))
    assert_blocked(run('if git commit -m "Generated with Claude Code"; then :; fi'))


def test_allow_keyword_word_inside_message():
    # A control keyword sitting inside a quoted message ("then run the tests") is an
    # ordinary word, not a leading keyword: the segment starts with `git`, so nothing is
    # peeled and the clean message passes.
    r = run('git commit -m "first do the parse, then run the tests"')
    assert_allowed(r)


def test_block_commit_attached_short_file_equals(tmp_path):
    # git reads `-F=MSG` as the filename `=MSG` (short options keep a leading `=`); the
    # parser must read that same file, not a stripped `MSG`.
    (tmp_path / "=MSG").write_text("Generated with Claude Code\n")
    (tmp_path / "MSG").write_text("Fix the parser\n")
    r = run("git commit -F=MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_commit_short_message_equals_byline():
    # `-m="Generated with Claude Code"` commits the message `=Generated with Claude Code`
    # (git keeps the `=`); the byline anchor must accept a leading `=` marker.
    r = run('git commit -m="Generated with Claude Code"')
    assert_blocked(r)


def test_allow_commit_attached_short_file_equals_clean(tmp_path):
    # The mirror of the block case: `-F=MSG` reading a clean `=MSG` must pass.
    (tmp_path / "=MSG").write_text("Fix the parser\n")
    r = run("git commit -F=MSG", cwd=tmp_path)
    assert_allowed(r)


def test_block_pr_body_hash_and_bullet_marker_byline():
    # A verb byline led by a markdown heading (#) or bullet (bullet char, :) marker must
    # trip the same as one led by * or >, since a PR body uses those markers.
    for marker in ("#", "•", ":"):
        body = "%s Generated with Claude Code" % marker
        assert_blocked(run('gh pr create --body "%s"' % body))


# --------------------------------------------------------------------------
# Spec-aligned boundary: a bare tool name is subject matter in free prose,
# authorship only in an author/trailer field (PR #193 finding T3).
# --------------------------------------------------------------------------

def test_allow_bare_tool_name_in_message_body():
    # A bare "Claude" line in a commit message is ambiguous with subject matter and is not
    # a form any tool emits (they write "Generated with Claude Code" plus Co-Authored-By,
    # both caught). Blocking it would false-block legitimate content, so free prose needs
    # an attribution cue; a bare name passes.
    r = run('git commit -m "Fix parser\n\nClaude"')
    assert_allowed(r)


def test_allow_pr_body_model_comparison_list():
    # A model-comparison list is legitimate content in a research/journalism repo. It must
    # not be mistaken for a byline just because each line is a bare tool name under a
    # bullet marker.
    body = "Tested models:\n\n- Claude\n- GPT-4\n- Gemini\n"
    r = run('gh pr create --body "%s"' % body)
    assert_allowed(r)


def test_block_bare_tool_name_in_author_field():
    # The strict field check still blocks a bare tool name in --author, because an author
    # field is a byline by definition (no subject-of-the-work reading).
    r = run('git commit --author "Claude <noreply@example.com>" -m "Fix parser"')
    assert_blocked(r)


# --------------------------------------------------------------------------
# Documented limitation: a message file written earlier in the SAME command
# line cannot be read by a pre-command hook (PR #193 finding T7).
# --------------------------------------------------------------------------

def test_allow_message_file_written_in_same_command(tmp_path):
    # A PreToolUse hook runs before the command, so it cannot read a file the same command
    # line creates: `printf ... >MSG && git commit -F MSG` writes the byline at run time,
    # and at hook time MSG does not hold it. Catching this would require modeling every
    # writer's output (printf/echo/tee), which would wreck the subject-matter allowance.
    # Same category as the command-substitution boundary; it passes by design.
    r = run("printf 'Generated with Claude Code\\n' >MSG && git commit -F MSG", cwd=tmp_path)
    assert_allowed(r)


# --------------------------------------------------------------------------
# Local codex 5.5/low findings on the PR #193 fix commit: no false blocks
# --------------------------------------------------------------------------

def test_allow_exported_identity_overwritten_clean():
    # A re-export overwrites: the commit is authored by the LATEST value (Joe), so a
    # stale earlier flagged value must not block. Modeling the env as a last-wins map,
    # not an append list, is what makes this a clean pass.
    r = run("export GIT_AUTHOR_NAME=Claude; export GIT_AUTHOR_NAME=Joe; git commit -m Fix")
    assert_allowed(r)


def test_allow_exported_identity_then_unset():
    # `unset` clears an earlier export before the commit, so the commit carries no tool
    # identity and must pass.
    r = run("export GIT_AUTHOR_NAME=Claude; unset GIT_AUTHOR_NAME; git commit -m Fix")
    assert_allowed(r)


def test_allow_inline_prefix_overrides_exported_identity():
    # An inline prefix overrides an earlier export for that command; the effective author
    # is the inline clean value, so it passes.
    r = run("export GIT_AUTHOR_NAME=Claude; GIT_AUTHOR_NAME=Joe git commit -m Fix")
    assert_allowed(r)


def test_block_tilde_quoted_real_target_in_cwd(tmp_path):
    # A quoted '~/MSG' is a literal path the shell resolves against cwd. Reading both the
    # literal cwd/~/MSG and the home-expanded path means the real target is still checked:
    # a byline in cwd/~/MSG blocks, never missed just because the ~ could not be expanded.
    tilde_dir = tmp_path / "~"
    tilde_dir.mkdir()
    (tilde_dir / "MSG").write_text("Generated with Claude Code\n")
    r = run("git commit -F '~/MSG'", cwd=tmp_path)
    assert_blocked(r)


# --------------------------------------------------------------------------
# Local codex 5.5/low round on head 6db857f: generic-AI and AI-prefixed bylines
# --------------------------------------------------------------------------

def test_block_generic_ai_byline_without_tool_name():
    # A byline can credit generic "AI" with no model name and still be an authorship
    # credit. "Generated with AI" / "Written by AI" slipped because AI was not a byline
    # token. Standalone AI (verb + with/by/using/via + AI, leading a line) now blocks.
    for msg in ("Generated with AI", "Written by AI", "Created by AI", "Produced using AI"):
        assert_blocked(run('git commit -m "%s"' % msg))


def test_block_ai_prefixed_verb_byline_with_named_tool():
    # "AI-assisted by Claude" slipped: the AI- prefix pushed the verb off the line-start
    # anchor and the trailing "by Claude" defeated the bare AI-tag full-line anchor. An
    # optional AI- prefix on the leading verb, still requiring a named-tool credit, closes
    # it without touching the subject-matter allowance below.
    for msg in ("AI-assisted by Claude", "AI-generated with GPT-4", "AI-written by ChatGPT"):
        assert_blocked(run('git commit -m "%s"' % msg))


def test_allow_ai_adjective_subject_after_verb():
    # The standalone-AI byline token must not fire on the adjective "AI-<noun>" of subject
    # matter, even right after a verb+with: "Built with AI-powered search" describes the
    # feature. The negative lookahead (AI not followed by a word char or hyphen) keeps the
    # adjective form out.
    assert_allowed(run('git commit -m "Built with AI-powered search for the archive"'))
    assert_allowed(run('gh pr create --body "Add AI-driven ranking to results"'))


# --------------------------------------------------------------------------
# Local codex 5.5/low round on head 5fe4c87: git long-option abbreviations
# and the `--` end-of-options terminator
# --------------------------------------------------------------------------

def test_block_abbreviated_author_option():
    # git parse-options accepts any unambiguous prefix of a long option, so --au / --auth
    # / --autho all set --author. The field value naming a tool must still block, whether
    # the value is a separate token or attached with `=`.
    for cmd in (
        'git commit --au "Claude <c@example.com>" -m Fix',
        'git commit --auth "Claude <c@example.com>" -m Fix',
        'git commit --autho="Claude <c@example.com>" -m Fix',
    ):
        assert_blocked(run(cmd))


def test_block_abbreviated_message_and_trailer_options():
    # --mess / --messag resolve to --message (text surface); --trail resolves to --trailer
    # (field surface). Both are unambiguous prefixes git accepts.
    assert_blocked(run('git commit --mess "Generated with Claude Code"'))
    assert_blocked(run('git commit --messag "Written by ChatGPT"'))
    assert_blocked(run('git commit -m Fix --trail "Co-authored-by: Claude <ai@example.com>"'))


def test_allow_abbreviated_nonattribution_option():
    # --am resolves to --amend (a boolean), not --message: an abbreviation that lands on an
    # untracked option must not be misclassified. The real message here is clean.
    assert_allowed(run('git commit --am -m "fix parser edge case"'))


def test_allow_ambiguous_abbreviation_not_classified():
    # --a is ambiguous (git rejects it: --all / --allow-empty / --amend / --author ...), so
    # the matcher resolves it to nothing and does not block. git would error before running,
    # so allowing it introduces no miss.
    assert_allowed(run('git commit --a "Claude <c@example.com>"'))


def test_allow_gh_unknown_abbrev_not_treated_as_flag():
    # gh/pflag does NOT do prefix matching, so --bod is an unknown flag gh rejects, not a
    # stand-in for --body. Abbreviation resolution is git-only; the matcher must not block
    # this as if it were a body credit (that would be a false positive on a command gh
    # itself refuses to run).
    assert_allowed(run('gh pr create --bod "Generated with Claude Code"'))


def test_allow_attribution_looking_pathspec_after_double_dash():
    # After a bare `--`, every token is a pathspec (a filename), never a message/option
    # value. `git commit -- --message "Generated with Claude Code"` commits paths literally
    # named `--message` and `Generated with Claude Code`; it sets no message, so blocking it
    # is a false positive. Scanning must stop at `--`.
    for cmd in (
        'git commit -- --message "Generated with Claude Code"',
        'git commit -- -m "Generated with Claude Code"',
        'git commit -m "real fix" -- "Generated with Claude Code.txt"',
    ):
        assert_allowed(run(cmd))


def test_block_attribution_before_double_dash_still_caught():
    # Stopping at `--` must only ignore what follows it: a real -m credit before the
    # terminator is still collected and blocked, so the terminator fix adds no miss.
    assert_blocked(run('git commit -m "Generated with Claude Code" -- somefile.txt'))


def test_block_git_commit_template_file_with_attribution(tmp_path):
    # git commit -t/--template <file> preloads the message editor with the file's contents,
    # which become the commit if the editor keeps them. It is another named message file, so
    # it is read like -F/--file -- and consistently with gh, whose --template is already read.
    (tmp_path / "MSG").write_text("Generated with Claude Code\n")
    assert_blocked(run("git commit --template MSG", cwd=tmp_path))
    assert_blocked(run("git commit -t MSG", cwd=tmp_path))
    assert_blocked(run("git commit --templ MSG", cwd=tmp_path))  # abbreviation resolves too


def test_allow_git_commit_template_file_clean(tmp_path):
    # A template with no attribution passes: the file surface only blocks on a byline, the
    # same as --file. This guards against the template classification over-blocking.
    (tmp_path / "MSG").write_text("Refactor the tokenizer for clarity\n")
    assert_allowed(run("git commit --template MSG", cwd=tmp_path))


# --------------------------------------------------------------------------
# Local codex 5.5/low round on head 87478f6: command-runner wrappers that
# hide the git/gh command word (command / exec / nohup / setsid)
# --------------------------------------------------------------------------

def test_block_command_wrapper_hiding_git_commit():
    # `command`, `exec`, `nohup`, `setsid` all run the command word that follows them, so
    # the watched `git commit` is still the real command and must still be seen.
    for w in ("command", "exec", "nohup", "setsid"):
        assert_blocked(run('%s git commit -m "Generated with Claude Code"' % w))


def test_block_command_wrapper_with_flags_and_nesting():
    # A wrapper's own leading flags are skipped, exec -a takes a value, and wrappers nest.
    assert_blocked(run('command -p git commit -m "Generated with Claude Code"'))
    assert_blocked(run('exec -a mygit git commit -m "Generated with Claude Code"'))
    assert_blocked(run('nohup command git commit -m "Generated with Claude Code"'))


def test_block_command_wrapper_on_gh():
    assert_blocked(run('command gh pr create --body "Generated with Claude Code"'))


def test_allow_command_v_lookup_is_not_a_run():
    # `command -v git` / `command -V git` look git up; they do not run a commit, so a
    # commit-shaped tail is not a real commit and must not block.
    assert_allowed(run("command -v git commit"))
    assert_allowed(run("command -V git"))


def test_allow_wrapper_without_watched_command():
    # A wrapper in front of a non-watched command still passes straight through.
    assert_allowed(run("nohup ./deploy.sh"))
    assert_allowed(run("exec ./run-tests.sh"))


# --------------------------------------------------------------------------
# codex 5.6-sol/xhigh round on head 870c4ee: common-form bypasses.
# Each block closes a form a normal workflow can produce that slipped past the
# "first token is literally git/gh, only git commit is watched" model.
# --------------------------------------------------------------------------

# -- command word reached by a path (/usr/bin/git, ./gh) --

def test_block_absolute_path_git_commit():
    # Automation invokes the interpreter by absolute path; the command word is still git.
    assert_blocked(run('/usr/bin/git commit -m "Generated with Claude Code"'))


def test_block_relative_path_gh_pr_create():
    assert_blocked(run('./gh pr create --body "Generated with Claude Code"'))


def test_allow_pathed_non_watched_command():
    assert_allowed(run("/usr/bin/ls -la"))


def test_allow_basename_lookalike_is_not_git():
    # A tool literally named mygit is not git; basename must be exact, not a suffix.
    assert_allowed(run('mygit commit -m "Generated with Claude Code"'))


# -- git merge writes a commit with a message/file, same as git commit --

def test_block_git_merge_message():
    assert_blocked(run('git merge --no-ff topic -m "Generated with Claude Code"'))


def test_block_git_merge_message_abbrev():
    # git accepts an unambiguous abbreviation of --message on merge too.
    assert_blocked(run('git merge topic --mess "Generated with Claude Code"'))


def test_block_git_merge_file(tmp_path):
    (tmp_path / "MSG").write_text("Generated with Claude Code\n")
    assert_blocked(run("git merge topic -F MSG", cwd=tmp_path))


def test_block_git_merge_identity_env():
    assert_blocked(run('GIT_AUTHOR_NAME=Claude git merge --no-ff topic -m "Merge branch"'))


def test_allow_git_merge_clean():
    assert_allowed(run('git merge --no-ff topic -m "Merge topic into main"'))


def test_allow_git_merge_no_message():
    assert_allowed(run("git merge topic"))


# -- gh pr merge sets the merge/squash commit message --

def test_block_gh_pr_merge_subject():
    assert_blocked(run('gh pr merge 123 --merge --subject "Generated with Claude Code" --body ok'))


def test_block_gh_pr_merge_body():
    assert_blocked(run('gh pr merge 123 --squash --body "Written by ChatGPT"'))


def test_block_gh_pr_merge_body_file(tmp_path):
    (tmp_path / "B.md").write_text("Generated with Claude Code\n")
    assert_blocked(run("gh pr merge 123 --merge --body-file B.md", cwd=tmp_path))


def test_allow_gh_pr_merge_method_flag_not_message():
    # -m here is the merge-method flag, not a message; a clean subject must pass.
    assert_allowed(run('gh pr merge 123 -m --subject "Merge pull request #123"'))


# -- gh pr/issue close and reopen carry a --comment body --

def test_block_gh_pr_close_comment():
    assert_blocked(run('gh pr close 123 --comment "Generated with Claude Code"'))


def test_block_gh_issue_close_comment_short():
    assert_blocked(run('gh issue close 45 -c "Generated with Claude Code"'))


def test_block_gh_pr_reopen_comment():
    assert_blocked(run('gh pr reopen 123 --comment "Written by ChatGPT"'))


def test_allow_gh_pr_close_clean():
    assert_allowed(run('gh pr close 123 --comment "Closing, superseded by #200"'))


def test_allow_gh_pr_close_no_comment():
    assert_allowed(run("gh pr close 123"))


# -- gh api posts record-writing requests via -f/--field/--input --

def test_block_gh_api_raw_field_body():
    assert_blocked(run(
        'gh api repos/O/R/issues/123/comments -f body="Generated with Claude Code"'))


def test_block_gh_api_field_body_long():
    assert_blocked(run(
        'gh api repos/O/R/issues/1/comments --raw-field body="Written by ChatGPT"'))


def test_block_gh_api_field_body_at_file(tmp_path):
    (tmp_path / "B.md").write_text("Generated with Claude Code\n")
    assert_blocked(run(
        "gh api repos/O/R/issues/1/comments -F body=@B.md", cwd=tmp_path))


def test_block_gh_api_input_file(tmp_path):
    (tmp_path / "body.json").write_text('{"body": "Generated with Claude Code"}\n')
    assert_blocked(run(
        "gh api repos/O/R/issues/1/comments --input body.json", cwd=tmp_path))


def test_allow_gh_api_clean_body():
    assert_allowed(run('gh api repos/O/R/issues/1/comments -f body="Thanks for the fix"'))


def test_allow_gh_api_non_body_field():
    assert_allowed(run("gh api repos/O/R/pulls/1 -f state=closed"))


def test_allow_gh_api_read():
    assert_allowed(run("gh api repos/O/R/pulls/1"))


# -- shell -c runners hide a git/gh command inside a script string --

def test_block_bash_c_git_commit():
    assert_blocked(run('bash -c \'git commit -m "Generated with Claude Code"\''))


def test_block_bash_lc_git_commit():
    assert_blocked(run('bash -lc \'git commit -m "Generated with Claude Code"\''))


def test_block_sh_c_git_commit():
    assert_blocked(run('sh -c \'git commit -m "Generated with Claude Code"\''))


def test_block_pathed_shell_c_git_commit():
    assert_blocked(run('/bin/bash -c \'git commit -m "Generated with Claude Code"\''))


def test_block_shell_c_author_field_through_recursion():
    # The recursion reuses the full matcher, so an author-field credit inside the -c script
    # is caught the same as an inline one.
    assert_blocked(run('sh -c "git commit --author=\'Claude <c@anthropic.com>\' -m Fix"'))


def test_allow_bash_c_clean():
    assert_allowed(run('bash -c \'git commit -m "Fix the parser"\''))


def test_allow_bash_c_non_watched():
    assert_allowed(run("bash -c 'ls -la && echo done'"))


def test_shell_c_deep_nesting_does_not_hang():
    # A pathological deep nest must return within the harness timeout (depth-bounded),
    # not recurse without bound. Correctness of the verdict at the bottom is secondary
    # to the never-wedge contract; assert it simply completes and exits cleanly.
    # Depth 8 exceeds any sane recursion cap while keeping the string small: each wrap
    # re-escapes the inner quotes, so the length grows geometrically and a large depth
    # would blow up the test itself, not the hook.
    cmd = "git commit -m ok"
    for _ in range(8):
        cmd = "bash -c '%s'" % cmd.replace("'", "'\\''")
    r = run(cmd)
    assert r.returncode in (0, 2)


# -- tool-token set omits common authorship-capable agents --

def test_block_generated_with_aider():
    assert_blocked(run('git commit -m "Generated with Aider"'))


def test_block_written_by_windsurf():
    assert_blocked(run('git commit -m "Written by Windsurf"'))


def test_block_byline_names_devin():
    assert_blocked(run('git commit -m "Fix parser\n\nGenerated by Devin"'))


def test_allow_human_named_devin_in_author_field():
    # Devin is a common human first name: a byline token, not a strict author-field token,
    # so a real person named Devin still authors a commit.
    assert_allowed(run('git commit --author="Devin Smith <devin@example.com>" -m Fix'))


def test_allow_devin_as_subject_matter():
    assert_allowed(run('git commit -m "Add the Devin integration adapter"'))


# -- generic-AI identity in an authorship field --

def test_block_ai_assistant_author():
    assert_blocked(run('git commit --author="AI Assistant <a@example.com>" -m Fix'))


def test_block_ai_bot_trailer():
    assert_blocked(run('git commit -m Fix --trailer "Co-Authored-By: AI Bot <a@x.com>"'))


def test_allow_human_first_name_ai():
    # A person whose name is Ai (a real given name) is not "AI Assistant"; bare Ai passes.
    assert_allowed(run('git commit --author="Ai Nakamura <ai@example.com>" -m Fix'))


# -- markdown +/ordered-list byline prefixes --

def test_block_plus_bullet_byline():
    assert_blocked(run('gh pr create --title Fix --body "+ Generated with Claude Code"'))


def test_block_ordered_list_byline():
    assert_blocked(run('gh pr create --title Fix --body "1. Generated with Claude Code"'))


def test_allow_plus_in_prose():
    assert_allowed(run('gh pr create --title Fix --body "Compute a + b for the totals"'))


# -- env -u clears an identity var that an earlier export set --

def test_allow_env_unset_clears_flagged_identity():
    # export sets an AI-looking author, then env -u removes it for the commit, so git uses
    # the clean configured identity. Blocking here is a false positive.
    assert_allowed(run(
        "export GIT_AUTHOR_NAME=Claude; env -u GIT_AUTHOR_NAME git commit -m Fix"))


def test_block_env_set_identity_still_blocks():
    # The unset path must not weaken the real case: an env-set AI identity still blocks.
    assert_blocked(run("env GIT_AUTHOR_NAME=Claude git commit -m Fix"))


# -- redirections must not hide the command word or split off its flags --

def test_block_leading_redirect_before_git():
    assert_blocked(run('>/dev/null git commit -m "Generated with Claude Code"'))


def test_block_interspersed_redirect_splits_message():
    assert_blocked(run('git commit >/dev/null -m "Generated with Claude Code"'))


def test_block_fd_redirect_before_message():
    assert_blocked(run('git commit 2>/dev/null -m "Generated with Claude Code"'))


def test_allow_trailing_redirect_clean_commit():
    assert_allowed(run('git commit -m "Fix the parser" >/dev/null 2>&1'))


# -- fail-open integrity: a giant payload must not exhaust memory or hang --

def test_huge_stdin_payload_fails_open():
    big = '{"tool_name": "Bash", "tool_input": {"command": "' + ("x" * 12_000_000) + '"}}'
    r = run("", raw_stdin=big)
    assert r.returncode == ALLOW


# --------------------------------------------------------------------------
# codex-connector re-review on head c643296: nine P2s, each a real form the
# round-6 fixes left uncovered. All resolvable from the command string, so
# each is fixed rather than documented.
# --------------------------------------------------------------------------

# -- env invoked by an absolute/relative path must be peeled like git/gh --

def test_block_pathed_env_identity_prefix():
    # /usr/bin/env is the canonical way to run a command with a set var; its basename is
    # env, so it must be peeled to reach the inner git commit's identity.
    assert_blocked(run('/usr/bin/env GIT_AUTHOR_NAME=Claude git commit -m Fix'))


def test_block_pathed_env_before_attributed_commit():
    assert_blocked(run('/usr/bin/env git commit -m "Generated with Claude Code"'))


def test_allow_pathed_env_clean_commit():
    assert_allowed(run('/usr/bin/env git commit -m "Fix the parser"'))


# -- env -C must move the run dir for a file read inside bash -c too --

def test_block_env_C_before_shell_c_file(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Generated with Claude Code\n")
    assert_blocked(run("env -C repo bash -c 'git commit -F MSG'", cwd=tmp_path))


# -- gh pr merge --author-email writes the merge commit author identity --

def test_block_gh_pr_merge_author_email_long():
    assert_blocked(run('gh pr merge 123 --squash --author-email noreply@openai.com --subject Fix'))


def test_block_gh_pr_merge_author_email_short():
    assert_blocked(run('gh pr merge 123 --merge -A "Claude <c@anthropic.com>" --subject Fix'))


def test_allow_gh_pr_merge_author_email_human():
    assert_allowed(run('gh pr merge 123 --merge -A jane@example.com --subject "Merge #123"'))


# -- gh api nested/bracketed prose keys (GraphQL variables) --

def test_block_gh_api_nested_input_body():
    assert_blocked(run(
        'gh api graphql -f query=mutation -f input[body]="Generated with Claude Code"'))


def test_allow_gh_api_nested_non_prose_key():
    assert_allowed(run('gh api graphql -f query=q -f input[state]=closed'))


# -- ANSI-C quoting must be decoded on the gh api field path too --

def test_block_gh_api_ansi_c_field():
    assert_blocked(run(
        "gh api repos/O/R/issues/1/comments -f body=$'Generated with Claude Code'"))


# -- reassigning an already-exported identity var updates the exported value --

def test_block_reassigned_exported_identity():
    # export sets a clean value, a later standalone assignment (same var, still exported)
    # overwrites it with a tool name, and the commit is authored as that.
    assert_blocked(run(
        "export GIT_AUTHOR_NAME=Joe; GIT_AUTHOR_NAME=Claude; git commit -m Fix"))


def test_allow_unexported_local_assignment():
    # A bare assignment with no prior export is shell-local, not passed to git, so a tool
    # name there does not author the commit and must not block.
    assert_allowed(run("GIT_AUTHOR_NAME=Claude; git commit -m Fix"))


# -- env -i starts an empty environment, dropping an earlier exported identity --

def test_allow_env_i_clears_exported_identity():
    assert_allowed(run(
        "export GIT_AUTHOR_NAME=Claude; env -i git commit -m Fix"))


def test_block_env_i_with_inline_identity_still_blocks():
    # -i wipes the inherited env, but an inline assignment after it is still passed to git.
    assert_blocked(run("env -i GIT_AUTHOR_NAME=Claude git commit -m Fix"))


# -- shell value-options before -c must not hide the script --

def test_block_bash_o_pipefail_before_c():
    assert_blocked(run(
        'bash -o pipefail -c \'git commit -m "Generated with Claude Code"\''))


def test_block_bash_rcfile_before_c(tmp_path):
    assert_blocked(run(
        'bash --rcfile /dev/null -c \'git commit -m "Generated with Claude Code"\''))


def test_allow_bash_o_pipefail_clean():
    assert_allowed(run('bash -o pipefail -c \'git commit -m "Fix the parser"\''))


# -- an explicit GET turns gh api fields into read-only query params --

def test_allow_gh_api_explicit_get_method():
    assert_allowed(run(
        'gh api --method GET repos/O/R/issues -f title="Generated with Claude Code"'))


def test_allow_gh_api_get_short_flag():
    assert_allowed(run(
        'gh api -X GET repos/O/R/issues -f title="Generated with Claude Code"'))


def test_block_gh_api_explicit_post_still_blocks():
    # An explicit POST is a write, so the guard must stay on when the method is named too.
    assert_blocked(run(
        'gh api --method POST repos/O/R/issues/1/comments -f body="Generated with Claude Code"'))


# --------------------------------------------------------------------------
# Round-8 connector re-review: six common-form fixes (three bypasses closed,
# three clean-command over-blocks removed). Each "allow more" fix ships with a
# "still blocks" guard so it cannot silently widen into a bypass.
# --------------------------------------------------------------------------

# -- F1: a robot-emoji byline behind a Markdown quote/bullet marker --
# _BYLINE_LEAD already lets the text-byline forms ride these markers; the
# emoji check must strip them too, or `- 🤖` / `> 🤖` slips a sign-off in.

def test_block_markdown_dash_robot_emoji_byline():
    assert_blocked(run('git commit -m "Fix parser\n\n- \U0001F916"'))


def test_block_quote_marker_robot_emoji_byline():
    assert_blocked(run('git commit -m "Fix parser\n\n> \U0001F916"'))


def test_allow_robot_emoji_midline_after_marker_is_subject():
    # A dash that starts a real list item of prose, with the emoji mid-line and no
    # attribution cue, is subject matter, not a sign-off: it must still pass.
    assert_allowed(run('git commit -m "Fix parser\n\n- render the \U0001F916 glyph"'))


# -- F4: `time -p` before the command (POSIX portability flag) --

def test_block_time_dash_p_wrapper_commit():
    assert_blocked(run('time -p git commit -m "Generated with Claude Code"'))


def test_allow_time_dash_p_clean_commit():
    assert_allowed(run('time -p git commit -m "Fix the parser"'))


# -- F5: `export NAME` (no value) then a standalone `NAME=value` assignment --
# The bare export marks NAME for export, so the later assignment reaches git.

def test_block_export_bare_then_assign_identity():
    assert_blocked(run(
        "export GIT_AUTHOR_NAME; GIT_AUTHOR_NAME=Claude; git commit -m Fix"))


def test_allow_export_bare_then_clean_assign():
    assert_allowed(run(
        'export GIT_AUTHOR_NAME; GIT_AUTHOR_NAME="Jane Doe"; git commit -m Fix'))


# -- F3: `git -c key=value` identity is last-wins per key --

def test_allow_git_c_identity_last_wins_clean():
    # git applies the last value, so a clean override of an earlier tool name commits
    # as the human: the hook must not block on the shadowed earlier value.
    assert_allowed(run("git -c user.name=Claude -c user.name=Jane commit -m Fix"))


def test_block_git_c_identity_last_wins_tool():
    # The reverse order ends on the tool name, which does author the commit: block.
    assert_blocked(run("git -c user.name=Jane -c user.name=Claude commit -m Fix"))


# -- F7: an unquoted trailing `#` comment is not part of the command --

def test_allow_trailing_comment_with_attributed_example():
    assert_allowed(run(
        'git commit -m "Fix parser" # git commit -m "Generated with Claude Code"'))


def test_block_hash_inside_quoted_message_still_scanned():
    # A `#` inside the quoted message is literal, not a comment start, so a byline
    # after it must still be seen (the comment strip must be quote-aware).
    assert_blocked(run('git commit -m "Fix #123\n\nGenerated with Claude Code"'))


def test_allow_hash_midword_in_message():
    # A `#` glued mid-word (issue#123) is literal in bash, not a comment: still clean.
    assert_allowed(run('git commit -m "Fix issue#123 parser"'))


# -- F8: `git commit --dry-run` creates no commit, so nothing enters the record --

def test_allow_dry_run_attributed_message():
    assert_allowed(run('git commit --dry-run -m "Generated with Claude Code"'))


def test_allow_dry_run_abbrev_message():
    # git resolves the unambiguous abbreviation `--dry` to --dry-run.
    assert_allowed(run('git commit --dry -m "Generated with Claude Code"'))


def test_block_no_verify_is_not_dry_run():
    # --no-verify (and -n) still create a commit, so an attributed message must block:
    # guard against the dry-run allowance widening to any dash-prefixed option.
    assert_blocked(run('git commit --no-verify -m "Generated with Claude Code"'))
    assert_blocked(run('git commit -n -m "Generated with Claude Code"'))


def test_block_real_commit_chained_after_dry_run():
    # The dry-run allowance must skip only its own segment: a real commit chained after
    # a dry-run still writes the record and must block.
    assert_blocked(run(
        'git commit --dry-run -m "preview" && git commit -m "Generated with Claude Code"'))


def test_block_ansi_c_escaped_apostrophe_byline():
    # Inside $'...', \' is an escaped apostrophe, so the quote does NOT end there and the
    # whole string is one word bash writes verbatim (with \n as a real newline, making a
    # trailing byline). shlex has no ANSI-C mode: it ends the single-quoted run at that
    # apostrophe and the rest of the line reads as unbalanced quoting, so the byline
    # reaches the record unscanned unless $'...' is decoded before tokenizing.
    r = run("git commit -m $'It\\'s fixed\\n\\nGenerated with Claude Code'")
    assert_blocked(r)


def test_allow_ansi_c_escaped_apostrophe_clean_message():
    # The same quoting with no attribution must still pass: decoding $'...' must not
    # turn an ordinary apostrophe into a block.
    r = run("git commit -m $'It\\'s a parser fix'")
    assert_allowed(r)


def test_allow_ansi_c_escaped_apostrophe_prose_mention():
    # Decoding must not widen the message check either: a tool named mid-sentence is
    # prose about the work, not a byline, and stays allowed once the quoting resolves.
    r = run("git commit -m $'Document what it\\'s generated with Claude Code'")
    assert_allowed(r)


def test_block_cd_double_dash_then_dash_prefixed_dir(tmp_path):
    # `cd -- -foo` ends option parsing, so `-foo` is the destination directory, not a
    # flag. Skipping it as an option sends the file lookup to the home directory and the
    # attributed MSG in -foo/ is never read.
    weird = tmp_path / "-foo"
    weird.mkdir()
    (weird / "MSG").write_text("Generated with Claude Code\n")
    r = run("cd -- -foo && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_pushd_then_relative_file_commit(tmp_path):
    # `pushd repo` changes the directory exactly as `cd repo` does; only the return stack
    # differs. Untracked, MSG resolves against the payload cwd and the attributed file in
    # repo/ is missed.
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Written by ChatGPT\n")
    r = run("pushd repo && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_popd_returns_to_attributed_dir(tmp_path):
    # popd returns to the directory pushd left, so the commit reads MSG from the payload
    # cwd. Treating popd as an unknown command would strand the base in sub/.
    (tmp_path / "MSG").write_text("Generated with Claude Code\n")
    sub = tmp_path / "sub"
    sub.mkdir()
    (sub / "MSG").write_text("Fix the parser\n")
    r = run("pushd sub && popd && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_allow_pushd_then_clean_file(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Fix the parser\n")
    r = run("pushd repo && git commit -F MSG", cwd=tmp_path)
    assert_allowed(r)


def test_block_pushd_dash_n_leaves_cwd(tmp_path):
    # `pushd -n repo` pushes onto the directory stack WITHOUT changing the working
    # directory, so the commit still reads MSG from the payload cwd. Following the -n
    # push into repo/ would scan a file the command never opens: it misses the real
    # attributed message here, and elsewhere false-blocks a clean commit.
    (tmp_path / "MSG").write_text("Generated with Claude Code\n")
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Fix the parser\n")
    r = run("pushd -n repo && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_allow_pushd_dash_n_clean_cwd_file(tmp_path):
    # The mirror image: with the attributed file only in repo/, a `pushd -n` commit
    # reads the clean cwd file and must not be blocked.
    (tmp_path / "MSG").write_text("Fix the parser\n")
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Generated with Claude Code\n")
    r = run("pushd -n repo && git commit -F MSG", cwd=tmp_path)
    assert_allowed(r)


def test_block_popd_dash_n_leaves_cwd(tmp_path):
    # `popd -n` drops a stack entry without changing the working directory, so the
    # commit still runs in sub/ and must be judged against sub/MSG.
    (tmp_path / "MSG").write_text("Fix the parser\n")
    sub = tmp_path / "sub"
    sub.mkdir()
    (sub / "MSG").write_text("Generated with Claude Code\n")
    r = run("pushd sub && popd -n && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_pushd_double_dash_then_dash_n_dir(tmp_path):
    # `pushd -- -n` enters a directory literally named -n: `--` ends option parsing, so
    # the -n option test must not reach past it. Verified against bash.
    weird = tmp_path / "-n"
    weird.mkdir()
    (weird / "MSG").write_text("Generated with Claude Code\n")
    (tmp_path / "MSG").write_text("Fix the parser\n")
    r = run("pushd -- -n && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_cd_double_dash_dash_is_still_oldpwd(tmp_path):
    # `cd -- -` is NOT a literal directory named `-`: bash substitutes $OLDPWD even
    # after `--`. Verified against bash. Treating it as a path would resolve the
    # message file under ./- and scan a file the command never opens.
    (tmp_path / "MSG").write_text("Generated with Claude Code\n")
    sub = tmp_path / "sub"
    sub.mkdir()
    (sub / "MSG").write_text("Fix the parser\n")
    # cd sub, then `cd -- -` returns to tmp_path, where MSG is attributed.
    r = run("cd sub && cd -- - && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_popd_indexed_leaves_cwd(tmp_path):
    # `popd +N` / `-N` remove an indexed entry from the directory stack; only the bare
    # form changes directory. Verified in bash: after `pushd a; pushd b`, `popd +1`
    # leaves you in b. Treating it as a plain pop would send the scan to a/ and let an
    # attributed b/MSG through, which is the bypass this pins shut.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Fix the parser\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Generated with Claude Code\n")
    r = run(f"pushd {a} && pushd {b} && popd +1 && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_popd_negative_index_leaves_cwd(tmp_path):
    # The `-N` spelling of the same rule: it also removes an indexed entry rather than
    # returning to the previous directory.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Fix the parser\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n")
    r = run(f"pushd {a} && pushd {b} && popd -1 && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_allow_popd_indexed_when_only_popped_entry_is_attributed(tmp_path):
    # The mirror image: the attributed file sits in the directory an indexed popd would
    # wrongly select, and the directory the commit really runs in is clean.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Generated with Claude Code\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Fix the parser\n")
    r = run(f"pushd {a} && pushd {b} && popd +1 && git commit -F MSG", cwd=tmp_path)
    assert_allowed(r)


def test_allow_ansi_c_escaped_backslash_is_literal_not_byline(tmp_path):
    # In `$'...'` a doubled backslash is a literal backslash, so bash passes
    # `Fix\n\nGenerated with Claude Code` as ONE line holding the two characters \ and n.
    # That is prose about a byline, not a byline. Decoding the escape twice (once when
    # rewriting the ANSI-C quote, once in the message scan) would manufacture a real
    # newline and false-block a clean commit.
    r = run(r"git commit -m $'Fix\\n\\nGenerated with Claude Code'", cwd=tmp_path)
    assert_allowed(r)


def test_block_ansi_c_single_backslash_newline_byline(tmp_path):
    # The contrast that keeps the test above honest: a single backslash IS a newline
    # escape, so this really does place the byline on its own line and must be blocked.
    r = run(r"git commit -m $'Fix\n\nGenerated with Claude Code'", cwd=tmp_path)
    assert_blocked(r)


def test_block_indexed_popd_shortens_what_the_next_popd_returns_to(tmp_path):
    # An indexed popd drops an entry from the middle of the stack, so the bare popd after
    # it skips past what it removed. Verified in bash: `pushd a; pushd b; popd +1; popd`
    # ends in the starting directory, because `+1` already consumed a. Tracking the
    # removal is what keeps the scan on the starting directory's MSG.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Fix the parser\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Fix the parser\n")
    (tmp_path / "MSG").write_text("Generated with Claude Code\n")
    r = run(f"pushd {a} && pushd {b} && popd +1 && popd && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_pushd_rotation_then_bare_popd_reaches_the_start(tmp_path):
    # The same reordering from the pushd side: a rotation moves the shell to an entry
    # already on the stack and rearranges what is left behind it. Verified in bash:
    # `pushd a; pushd b; pushd +1` lands in a, and the popd after it ends in the
    # starting directory rather than back in b.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Fix the parser\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Fix the parser\n")
    (tmp_path / "MSG").write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n")
    r = run(f"pushd {a} && pushd {b} && pushd +1 && popd && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_pushd_rotation_lands_on_the_rotated_entry(tmp_path):
    # The rotation itself moves the shell, before any popd: `pushd a; pushd b; pushd +1`
    # leaves bash in a. Holding at b would scan the wrong directory outright.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Generated with Claude Code\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Fix the parser\n")
    r = run(f"pushd {a} && pushd {b} && pushd +1 && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_pushd_dash_n_rotation_leaves_cwd(tmp_path):
    # `-n` suppresses the move in the argument-less forms too, so the rotation happens but
    # the shell stays put. Verified in bash: after `pushd a; pushd b`, all of `pushd -n`,
    # `pushd -n +1` and `pushd -n -1` stay in b. Rotating the scan to a here would both
    # miss an attributed b/MSG and false-block a clean one, which is the failure the
    # holding rule exists to prevent.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Fix the parser\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Generated with Claude Code\n")
    r = run(f"pushd {a} && pushd {b} && pushd -n +1 && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_allow_bare_pushd_dash_n_leaves_the_listing_intact(tmp_path):
    # Bare `pushd -n` is the one rotation form that changes nothing at all -- no move, and
    # the listing is untouched -- so the popd after it still returns where the matching
    # pushd left. Verified in bash: `pushd a; pushd b; pushd -n; popd` lands in a. Clearing
    # the tracked stack here would strand the scan in b and false-block this clean commit.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Fix the parser\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Generated with Claude Code\n")
    r = run(f"pushd {a} && pushd {b} && pushd -n && popd && git commit -F MSG", cwd=tmp_path)
    assert_allowed(r)


def test_block_pushd_dash_n_rotation_reorders_what_popd_returns_to(tmp_path):
    # The rotation still lands behind the working directory, so the popd after it goes
    # somewhere a plain pair would not. Verified in bash: `pushd a; pushd b; pushd -n +1;
    # popd` ends in the starting directory rather than in a.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Fix the parser\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Fix the parser\n")
    (tmp_path / "MSG").write_text("Generated with Claude Code\n")
    r = run(f"pushd {a} && pushd {b} && pushd -n +1 && popd && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_bare_pushd_swaps_the_top_two_entries(tmp_path):
    # Argument-less `pushd` swaps the top two entries rather than rotating by a position,
    # so after `pushd a; pushd b` it also lands in a. Same destination as `pushd +1` here,
    # but by a different rule, and both must be followed.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Generated with Claude Code\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Fix the parser\n")
    r = run(f"pushd {a} && pushd {b} && pushd && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_pushd_dash_n_becomes_the_next_popd_destination(tmp_path):
    # `pushd -n b` does not move the shell, but it does insert b as the next entry a popd
    # returns to. Verified in bash: `pushd a; pushd -n b; popd` ends in b, not in the
    # starting directory. Recording it rather than discarding it is what keeps b/MSG in
    # the scan's path.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Fix the parser\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Generated with Claude Code\n")
    (tmp_path / "MSG").write_text("Fix the parser\n")
    r = run(f"pushd {a} && pushd -n {b} && popd && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_pushd_dash_n_then_two_popds_reach_the_start(tmp_path):
    # The rest of that stack stays in order behind the inserted entry: a second popd
    # returns to where the whole sequence began. Verified in bash: `pushd a; pushd -n b;
    # popd; popd` ends in the starting directory.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Fix the parser\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Fix the parser\n")
    (tmp_path / "MSG").write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n")
    r = run(f"pushd {a} && pushd -n {b} && popd && popd && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_popd_index_zero_moves_like_bare_popd(tmp_path):
    # `popd +0` names entry 0 of the dirs listing, which IS the working directory, so it
    # is the one indexed form that moves the shell -- and it moves exactly where a bare
    # popd would. Verified in bash: `pushd a; pushd b; popd +0` lands in a. Holding at b
    # here would not be a conservative miss, it would be a bypass: git reads a/MSG while
    # the scan reads b/MSG.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Generated with Claude Code\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Fix the parser\n")
    r = run(f"pushd {a} && pushd {b} && popd +0 && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_popd_negative_index_reaching_entry_zero(tmp_path):
    # The same move spelled from the far end: `-N` counts back from the deepest entry, so
    # with two pushes `-2` resolves to entry 0 and behaves exactly like `popd +0`.
    # Verified in bash: `pushd a; pushd b; popd -2` lands in a, while `popd -1` stays in b.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Co-Authored-By: Claude <noreply@anthropic.com>\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Fix the parser\n")
    r = run(f"pushd {a} && pushd {b} && popd -2 && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_popd_dash_n_index_zero_leaves_cwd(tmp_path):
    # `-n` suppresses the directory change in every form, including the one index that
    # would otherwise move: `popd -n +0` stays in b. So the `-n` test has to come first,
    # before the index is considered at all.
    a = tmp_path / "a"
    a.mkdir()
    (a / "MSG").write_text("Fix the parser\n")
    b = tmp_path / "b"
    b.mkdir()
    (b / "MSG").write_text("Generated with Claude Code\n")
    r = run(f"pushd {a} && pushd {b} && popd -n +0 && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_allow_tracked_pushd_popd_pairs_still_return(tmp_path):
    # The guard against over-correcting: clearing the stack must only happen on the forms
    # that desynchronize it. A plain push/pop pair is still fully mirrored, so popd keeps
    # returning to the directory pushd left and a clean commit there stays allowed.
    sub = tmp_path / "sub"
    sub.mkdir()
    (sub / "MSG").write_text("Generated with Claude Code\n")
    (tmp_path / "MSG").write_text("Fix the parser\n")
    r = run(f"pushd {sub} && popd && git commit -F MSG", cwd=tmp_path)
    assert_allowed(r)
