"""Contract tests for the no-ai-attribution PreToolUse hook.

The hook blocks a git/gh command that would write AI authorship credit into the
project record, before it runs. It reads the Claude Code PreToolUse payload on
stdin and exits 2 to deny (reason on stderr) or 0 to allow.

These tests drive the implementation: they define exactly which command shapes
must block, which must pass, and how the hook fails open. Run:
    python -m pytest hooks/tests/test_no_ai_attribution.py -q
"""
import json
import subprocess
import sys
from pathlib import Path

HOOK = Path(__file__).resolve().parent.parent / "no-ai-attribution.py"

DENY = 2
ALLOW = 0


def run(command, tool_name="Bash", cwd=None, raw_stdin=None, timeout=30):
    """Invoke the hook as a subprocess with a PreToolUse payload; return CompletedProcess.

    timeout guards the never-wedge contract: if the hook hangs (e.g. reading a FIFO),
    subprocess.run raises TimeoutExpired and kills the child, so a hang fails the test
    loudly instead of freezing the suite.
    """
    if raw_stdin is None:
        payload = {"tool_name": tool_name, "tool_input": {"command": command}}
        if cwd is not None:
            payload["cwd"] = str(cwd)
        stdin = json.dumps(payload)
    else:
        stdin = raw_stdin
    return subprocess.run(
        [sys.executable, str(HOOK)],
        input=stdin,
        capture_output=True,
        text=True,
        timeout=timeout,
    )


def assert_blocked(r):
    # A real deny is exit 2 with the hook's own reason on stderr. Requiring the
    # sentinel distinguishes a genuine block from a crash (a missing script also
    # exits 2, with a traceback instead of the reason).
    assert r.returncode == DENY and "no-ai-attribution" in r.stderr.lower(), (
        r.returncode,
        r.stderr,
    )


def assert_allowed(r):
    assert r.returncode == ALLOW, (r.returncode, r.stderr)


# --------------------------------------------------------------------------
# MUST BLOCK: inline / body attribution (the message-text surface)
# --------------------------------------------------------------------------

def test_block_commit_inline_generated_with():
    r = run('git commit -m "Fix parser\n\n\U0001F916 Generated with Claude Code"')
    assert_blocked(r)


def test_block_commit_inline_coauthored_trailer_in_message():
    r = run('git commit -m "Fix parser\n\nCo-Authored-By: GPT-4 <noreply@openai.com>"')
    assert_blocked(r)


def test_block_commit_am_cluster_robot_emoji():
    r = run('git commit -am "\U0001F916 tidy up"')
    assert_blocked(r)


def test_block_chained_second_commit_attributed():
    r = run('git add -A && git commit -am "Generated by Claude"')
    assert_blocked(r)


def test_block_pr_create_body_generated_with():
    r = run('gh pr create --body "Generated with Claude Code"')
    assert_blocked(r)


def test_block_pr_create_title_written_by():
    r = run('gh pr create --title "Written by Claude" --body "clean body"')
    assert_blocked(r)


def test_block_pr_comment_coauthored_with():
    r = run('gh pr comment 5 --body "Co-authored with Claude"')
    assert_blocked(r)


def test_block_issue_comment_ai_generated():
    r = run('gh issue comment 7 --body "AI-generated summary. \U0001F916"')
    assert_blocked(r)


def test_block_pr_review_body_attribution():
    r = run('gh pr review 5 --body "Written by Copilot"')
    assert_blocked(r)


# --------------------------------------------------------------------------
# MUST BLOCK: the four conceded flag-level bypasses (#177)
# --------------------------------------------------------------------------

def test_block_commit_trailer_flag_model():
    r = run("git commit -m \"Fix\" --trailer 'Co-Authored-By: Claude <noreply@anthropic.com>'")
    assert_blocked(r)


def test_block_commit_author_flag_bot_email():
    r = run("git commit -m \"Fix\" --author='Claude <bot@example.com>'")
    assert_blocked(r)


def test_block_commit_author_flag_tool_name_human_email():
    # The author field is authorship by definition: a tool token blocks even with a
    # non-bot email.
    r = run("git commit -m \"Fix\" --author='Codex <someone@example.com>'")
    assert_blocked(r)


def test_block_pr_edit_body_attribution():
    r = run('gh pr edit 3 --body "Written by ChatGPT"')
    assert_blocked(r)


def test_block_pr_create_template_file_attributed(tmp_path):
    tpl = tmp_path / "T.md"
    tpl.write_text("## Summary\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n")
    r = run("gh pr create --template T.md", cwd=tmp_path)
    assert_blocked(r)


def test_block_pr_edit_body_file_robot_emoji(tmp_path):
    body = tmp_path / "B.md"
    body.write_text("Updates the parser.\n\n\U0001F916 Generated with Claude Code\n")
    r = run("gh pr edit 3 --body-file B.md", cwd=tmp_path)
    assert_blocked(r)


def test_block_commit_file_message_attributed(tmp_path):
    msg = tmp_path / "MSG"
    msg.write_text("Fix the parser\n\n\U0001F916 Generated with Claude Code\n")
    r = run("git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


# --------------------------------------------------------------------------
# MUST BLOCK: environment-variable prefixes (the command word is not seg[0])
# --------------------------------------------------------------------------

def test_block_pr_create_env_prefixed_body():
    # GH_TOKEN=... gh pr create is a common scripted form; the command word is not
    # the first token, so the hook must step over the assignment to find it.
    r = run('GH_TOKEN=xxx gh pr create --body "Generated with Claude Code"')
    assert_blocked(r)


def test_block_commit_env_identity_tool_name():
    # Setting authorship through the environment is the twin of --author.
    r = run('GIT_AUTHOR_NAME=Claude git commit -m "Fix the parser"')
    assert_blocked(r)


def test_block_commit_env_wrapper_identity():
    # Same authorship bypass through the `env` command wrapper.
    r = run('env GIT_AUTHOR_NAME=Claude git commit -m "Fix the parser"')
    assert_blocked(r)


def test_block_ai_assisted_standalone_byline():
    # A standalone "AI-assisted" sign-off line is a byline, not subject matter.
    r = run('git commit -m "Refactor auth\n\nAI-assisted"')
    assert_blocked(r)


def test_block_commit_dash_c_identity_config():
    # git -c user.name=... sets the commit identity inline, the same as --author.
    r = run('git -c user.name=Claude -c user.email=bot@example.com commit -m "Fix parser"')
    assert_blocked(r)


def test_block_commit_env_split_string_identity():
    # env -S packs the command into one re-split string; the inner identity must be seen.
    r = run('env -S "GIT_AUTHOR_NAME=Claude git commit -m Fix"')
    assert_blocked(r)


# --------------------------------------------------------------------------
# MUST BLOCK: shell syntax that hides the command word from a naive tokenizer
# --------------------------------------------------------------------------

def test_block_spaceless_operator_chained_commit():
    # No spaces around && : plain shlex.split leaves "-A&&" as one token.
    r = run('git add -A&& git commit -m "Generated by Claude"')
    assert_blocked(r)


def test_block_spaceless_semicolon_commit():
    r = run('true;git commit -m "Written by Claude"')
    assert_blocked(r)


def test_block_subshell_wrapped_commit():
    r = run('(git commit -m "Generated by Claude")')
    assert_blocked(r)


def test_block_gh_global_repo_flag_before_pr():
    r = run('gh -R owner/repo pr create --body "Generated with Claude Code"')
    assert_blocked(r)


def test_block_gh_repo_equals_flag_before_comment():
    r = run('gh --repo=owner/repo pr comment 5 --body "Written by ChatGPT"')
    assert_blocked(r)


def test_block_gh_value_taking_global_before_pr():
    # A value-taking global (here --hostname) must not be mistaken for the group; the
    # command is identified by the pr+create tokens, not by position.
    r = run('gh --hostname github.com pr create --body "Generated with Claude Code"')
    assert_blocked(r)


def test_block_gh_issue_create_body_attributed():
    r = run('gh issue create --title "Bug" --body "\U0001F916 Generated with Claude Code"')
    assert_blocked(r)


# --------------------------------------------------------------------------
# MUST ALLOW: legitimate tool mentions, human authorship, unwatched commands
# --------------------------------------------------------------------------

def test_allow_spaceless_operator_clean_commit():
    r = run('git add -A&& git commit -m "Fix the parser"')
    assert_allowed(r)


def test_allow_gh_global_repo_flag_clean_body():
    r = run('gh -R owner/repo pr create --title "Add X" --body "Adds X. Verify by running it."')
    assert_allowed(r)


def test_allow_commit_dash_c_nonidentity_config():
    r = run('git -c core.editor=vim commit -m "Fix the parser"')
    assert_allowed(r)


def test_allow_commit_dash_c_human_identity():
    r = run('git -c user.name="Jane Doe" commit -m "Fix the parser"')
    assert_allowed(r)


def test_allow_robot_emoji_as_subject_matter():
    # A robot emoji embedded in prose describes the subject, not authorship.
    r = run('git commit -m "Fix \U0001F916 emoji rendering in Slack messages"')
    assert_allowed(r)


def test_allow_robot_emoji_trailing_decoration_no_cue():
    # A trailing robot emoji with no attribution cue on its line is decoration, not a
    # byline.
    r = run('git commit -m "Restart the bot \U0001F916"')
    assert_allowed(r)


def test_allow_ai_generated_as_subject_matter():
    # Journalism repos discuss AI-generated content constantly; the phrase embedded in
    # a sentence describes the subject of the change, not who authored it.
    r = run('git commit -m "Detect AI-generated images in uploads"')
    assert_allowed(r)


def test_allow_ai_assisted_as_subject_matter():
    r = run('gh pr create --title "Analysis" --body "Add AI-assisted analysis to the dashboard"')
    assert_allowed(r)


def test_allow_env_prefixed_clean_body():
    r = run('GH_TOKEN=xxx gh pr create --title "Add X" --body "Adds X. Verify by running the tests."')
    assert_allowed(r)


def test_allow_env_identity_human():
    r = run('GIT_AUTHOR_NAME="Jane Doe" git commit -m "Fix the parser"')
    assert_allowed(r)

def test_allow_commit_subject_names_tool():
    r = run('git commit -m "Fix the Claude API client parser"')
    assert_allowed(r)


def test_allow_pr_body_documents_tool():
    r = run('gh pr create --title "Docs" --body "Document the Claude API client and OpenAI fallback"')
    assert_allowed(r)


def test_allow_commit_author_human():
    r = run("git commit -m \"Fix\" --author='Jane Doe <jane@example.com>'")
    assert_allowed(r)


def test_allow_commit_trailer_human_coauthor():
    r = run("git commit -m \"Fix\" --trailer 'Co-Authored-By: Jane Doe <jane@example.com>'")
    assert_allowed(r)


def test_allow_commit_author_github_noreply_not_bot():
    # The repo's own author convention: NNN+user@users.noreply.github.com must not
    # read as a bot email.
    r = run("git commit -m \"Fix\" --author='Jane <27182+jane@users.noreply.github.com>'")
    assert_allowed(r)


def test_allow_verb_with_by_no_tool_token():
    # "built"/"written"/"by" are common words; without a tool token nearby they are
    # not attribution.
    r = run('git commit -m "Built by the team, written by hand"')
    assert_allowed(r)


def test_allow_clean_pr_body_verify_by_running():
    r = run('gh pr create --title "Add X" --body "Adds X. Verify by running the tests."')
    assert_allowed(r)


def test_allow_non_watched_command():
    r = run("ls -la")
    assert_allowed(r)


def test_allow_git_log_author_grep_not_a_commit():
    r = run("git log --author=Claude")
    assert_allowed(r)


def test_allow_commit_file_from_stdin_dash():
    r = run("git commit -F -")
    assert_allowed(r)


def test_allow_bare_commit_editor():
    r = run("git commit")
    assert_allowed(r)


def test_allow_pr_create_template_file_clean(tmp_path):
    tpl = tmp_path / "T.md"
    tpl.write_text("## Summary\n\nExplains the change and how to verify it.\n")
    r = run("gh pr create --template T.md", cwd=tmp_path)
    assert_allowed(r)


# --------------------------------------------------------------------------
# MUST BLOCK: shell structure a token stream erases (newline separators, cd)
# --------------------------------------------------------------------------

def test_block_newline_separated_commit():
    # A literal newline separates two commands the same as `;`. shlex drops it as
    # whitespace, so the attributed second command must still be seen.
    r = run('printf ok\ngit commit -m "Written by ChatGPT"')
    assert_blocked(r)


def test_allow_newline_separated_clean_commits():
    # The common multiline form: separate clean commands on their own lines.
    r = run('git add -A\ngit commit -m "Fix the parser"')
    assert_allowed(r)


def test_block_cd_then_relative_file_commit(tmp_path):
    # `cd repo && git commit -F MSG` resolves MSG in repo/, not the payload cwd.
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Written by ChatGPT\n")
    r = run("cd repo && git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_git_dash_C_relative_file(tmp_path):
    # `git -C repo` changes the directory relative file args resolve against.
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("\U0001F916 Generated with Claude Code\n")
    r = run("git -C repo commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_allow_cd_then_relative_file_clean(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Fix the parser\n")
    r = run("cd repo && git commit -F MSG", cwd=tmp_path)
    assert_allowed(r)


def test_block_env_split_string_attached():
    # env -S accepts the attached form `-S'...'`, not only `-S "..."`.
    r = run("env -S'GIT_AUTHOR_NAME=Claude git commit -m Fix'")
    assert_blocked(r)


# --------------------------------------------------------------------------
# MUST BLOCK: gh edit title, gh issue edit, and more attribution connectors
# --------------------------------------------------------------------------

def test_block_pr_edit_title_attribution():
    # gh pr edit --title writes to the record too, not only --body.
    r = run('gh pr edit 3 --title "Written by ChatGPT"')
    assert_blocked(r)


def test_block_issue_edit_body_attribution():
    r = run('gh issue edit 3 --body "Written by ChatGPT"')
    assert_blocked(r)


def test_block_commit_generated_using_connector():
    r = run('git commit -m "Generated using Claude Code"')
    assert_blocked(r)


def test_block_commit_generated_via_connector():
    r = run('git commit -m "Generated via ChatGPT"')
    assert_blocked(r)


def test_block_byline_generated_with_still_blocks():
    # Regression: the canonical trailing byline stays blocked after the byline is
    # constrained to line-leading position (the fix for the subject-matter allow).
    r = run('git commit -m "Fix parser\n\nGenerated with Claude Code"')
    assert_blocked(r)


# --------------------------------------------------------------------------
# MUST ALLOW: an attribution verb + tool as mid-sentence subject matter
# --------------------------------------------------------------------------

def test_allow_generated_by_tool_as_subject_matter():
    # "summaries generated by Claude" describes what the change handles, not who wrote
    # the commit. In an AI-focused repo this phrasing is common and must pass.
    r = run('git commit -m "Handle summaries generated by Claude"')
    assert_allowed(r)


def test_allow_pr_body_content_written_by_model_as_subject():
    r = run('gh pr create --title "Moderation" --body "Flag posts written by GPT bots"')
    assert_allowed(r)


# --------------------------------------------------------------------------
# Named-file reads: bounded and regular-file-only (never wedge, never OOM)
# --------------------------------------------------------------------------

def test_fifo_body_file_fails_open_without_hanging(tmp_path):
    # A FIFO body-file would block a naive read forever. The hook must treat a
    # non-regular file as unreadable and fail open, returning quickly.
    import os
    fifo = tmp_path / "PIPE"
    os.mkfifo(fifo)
    r = run("gh pr create --body-file PIPE", cwd=tmp_path, timeout=15)
    assert_allowed(r)


def test_large_regular_body_file_with_early_attribution_blocks(tmp_path):
    # A large but regular file is read up to the cap; attribution near the top is
    # still caught, and the read does not exhaust memory.
    body = tmp_path / "BIG.md"
    body.write_text("\U0001F916 Generated with Claude Code\n" + ("filler line\n" * 200000))
    r = run("gh pr create --body-file BIG.md", cwd=tmp_path)
    assert_blocked(r)


# --------------------------------------------------------------------------
# Fail open: never wedge a session on a payload the hook cannot read
# --------------------------------------------------------------------------

def test_failopen_malformed_json():
    r = run(None, raw_stdin="{ this is not json")
    assert_allowed(r)


def test_failopen_empty_stdin():
    r = run(None, raw_stdin="")
    assert_allowed(r)


def test_failopen_non_bash_tool():
    r = run('git commit -m "\U0001F916 Generated with Claude Code"', tool_name="Write")
    assert_allowed(r)


def test_failopen_missing_tool_input():
    r = run(None, raw_stdin=json.dumps({"tool_name": "Bash"}))
    assert_allowed(r)


def test_failopen_missing_template_file_allows(tmp_path):
    # A named template that does not exist cannot be read; do not wedge the command.
    r = run("gh pr create --template MISSING.md", cwd=tmp_path)
    assert_allowed(r)


def test_unbalanced_quotes_falls_back_to_raw_scan():
    # shlex cannot tokenize this, but the attribution is still visible in the raw
    # command, so it must still block.
    r = run('git commit -m "\U0001F916 Generated with Claude Code')
    assert_blocked(r)


# --------------------------------------------------------------------------
# MUST BLOCK: shell forms a stricter reviewer found still slipped through
# --------------------------------------------------------------------------

def test_coauthor_scan_is_not_quadratic_on_blank_lines():
    # A clean commit message of many blank lines must be cleared quickly. The quadratic
    # case is the non-matching one: a leading ^\s* in the Co-Authored-By regex under re.M
    # greedily eats to the end from every line anchor and fails, rescanning O(n^2). A
    # tight timeout hangs on that; the linear ^[ \t]* form returns in well under a second.
    # (A message that does end in a matching Co-Authored-By line matches on the first
    # anchor and is fast even with the bug, so it would not exercise the backtracking.)
    msg = "\n" * 32000 + "Fixed the parser"
    r = run('git commit -m "%s"' % msg, timeout=5)
    assert_allowed(r)


def test_block_env_chdir_attached_relative_file(tmp_path):
    # env -Crepo (attached short form) sets the run dir the same as env -C repo, so a
    # relative -F file resolves in repo/, not the payload cwd.
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Generated with Claude Code\n")
    r = run("env -Crepo git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_env_double_dash_then_identity():
    # env -- ends option parsing but still reads NAME=value operands as assignments, so
    # the identity var after -- must reach the same check as a bare identity prefix.
    r = run("env -- GIT_AUTHOR_NAME=Claude git commit -m Fix")
    assert_blocked(r)


def test_block_commit_ansi_c_quoted_byline():
    # $'...\n...' is ANSI-C quoting: bash decodes \n to a real newline and commits a
    # real trailing byline, but shlex keeps the literal backslash-n, so the byline slips
    # unless the escapes are decoded before the line-anchored check.
    r = run("git commit -m $'Fix parser\\n\\nGenerated with Claude Code'")
    assert_blocked(r)


def test_block_subshell_cd_does_not_hide_payload_cwd_file(tmp_path):
    # (cd repo) runs in a subshell, so its cd does not move the later git commit, which
    # still reads ./MSG at the payload cwd. Tracking the cd as if it persisted would read
    # the clean repo/MSG and miss the attributed ./MSG.
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Fix the parser\n")
    (tmp_path / "MSG").write_text("Generated with Claude Code\n")
    r = run("(cd repo); git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_block_cd_to_missing_dir_still_checks_payload_cwd(tmp_path):
    # A failed `cd nonexistent` leaves the shell in the payload cwd, where git reads the
    # attributed ./MSG. Switching the effective dir to the missing target would read
    # nothing and miss it.
    (tmp_path / "MSG").write_text("Generated with Claude Code\n")
    r = run("cd nonexistent; git commit -F MSG", cwd=tmp_path)
    assert_blocked(r)


def test_allow_cd_clean_file_in_both_dirs(tmp_path):
    # Checking both the tracked dir and the payload cwd must not block when both files
    # are clean: the legitimate cd-into-repo commit still passes.
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "MSG").write_text("Fix the parser\n")
    (tmp_path / "MSG").write_text("Fix the parser\n")
    r = run("cd repo && git commit -F MSG", cwd=tmp_path)
    assert_allowed(r)
